version: '3'
services:
  nlp100:
    build: .
    image: nlp100
  sut:
    image: kiwicom/dgoss
    environment:
      GOSS_FILES_PATH: /goss
      GOSS_FILES_STRATEGY: cp
    command: /usr/local/bin/dgoss run nlp100
    volumes:
      - ./goss:/goss
      - /var/run/docker.sock:/var/run/docker.sock
